# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RGAMobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

    use_frameworks!

    pod 'Moya'
    pod 'Reusable'
    pod 'SDWebImage', '~> 4.0'
    pod 'R.swift'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RealmSwift'
    pod 'RxRealm'
    
  target 'RGAMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RGAMobileUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

